In [1]:
import pandas as pd

In [2]:
f_df = pd.read_csv("f.csv")
h56_df = pd.read_csv("h56.csv")
harness_df = pd.read_csv("harness.csv")

In [3]:
f_df

                             tuple  count  G_original  G_sigmoid  G_relu_sum
0                     (0, 0, 0, 0)      0    0.000000   0.500000        0.00
1         (0.01, 0.01, 0.01, 0.01)      0    0.000000   0.268941        0.00
2     (-0.01, -0.01, -0.01, -0.01)      4    0.039801   0.731059        0.04
3  (-0.01, -0.01, -0.01, -0.01, 1)      4    0.039801   0.731059        0.04
4     (0.01, 0.01, 0.01, 0.01, -1)      1    0.693147   1.000000        1.00
5      (0.01, 0.01, 0.01, 0.01, 1)      0    0.000000   0.268941        0.00
6         (-0.5, -0.5, -0.5, -0.5)      4    1.621860   1.000000        2.00

In [4]:
h56_df

,G,iterations,optimized val,edges cut by config,optimize func of t1,regularization,filename
0,G_original,30,-8.851915e+03,60,-568.163703,NaN,data/t1_matrix_test_0.npz
1,G_original,13,-3.843888e+02,60,-305.163703,ridge,data/t1_matrix_test_1.npz
2,G_original,17,-6.694284e+01,60,-31.858630,bound_sigmoid,data/t1_matrix_test_2.npz
3,G_original,5,-6.134109e+01,60,-62.463081,bound_softmax,data/t1_matrix_test_3.npz
4,G_sigmoid,0,-6.000000e+01,60,-192.000000,NaN,data/t1_matrix_test_4.npz
5,G_sigmoid,0,-2.500000e+01,60,71.000000,ridge,data/t1_matrix_test_5.npz
6,G_sigmoid,82,-1.487374e+02,150,-175.142720,bound_sigmoid,data/t1_matrix_test_6.npz
7,G_sigmoid,0,-6.000000e+01,60,-110.000000,bound_softmax,data/t1_matrix_test_7.npz
8,G_relu_sum,13,-1.049458e+292,152,-3232.000000,NaN,data/t1_matrix_test_8.npz
9,G_relu_sum,2,-1.842417e+08,60,-2969.000000,ridge,data/t1_matrix_test_9.npz
10,G_relu_sum,17,-7.499976e+01,60,-34.299587,bound_sigmoid,data/t1_matrix_test_10.npz
11,G_relu_sum,4,-6.806250e+01,60,-69.570766,bound_softmax,data/t1_matrix_test_11.npz

In [5]:
harness_df

     (k,d)           G            reg        count                  filename
0   (3, 3)  G_original            NaN    tensor(0)   data/harness_small0.npz
1   (3, 3)  G_original          ridge    tensor(7)   data/harness_small1.npz
2   (3, 3)  G_original  bound_sigmoid    tensor(0)   data/harness_small2.npz
3   (3, 3)  G_original  bound_softmax    tensor(0)   data/harness_small3.npz
4   (3, 3)   G_sigmoid            NaN    tensor(0)   data/harness_small4.npz
5   (3, 3)   G_sigmoid          ridge    tensor(0)   data/harness_small5.npz
6   (3, 3)   G_sigmoid  bound_sigmoid    tensor(9)   data/harness_small6.npz
7   (3, 3)   G_sigmoid  bound_softmax    tensor(9)   data/harness_small7.npz
8   (3, 3)  G_relu_sum            NaN    tensor(0)   data/harness_small8.npz
9   (3, 3)  G_relu_sum          ridge    tensor(7)   data/harness_small9.npz
10  (3, 3)  G_relu_sum  bound_sigmoid    tensor(0)  data/harness_small10.npz
11  (3, 3)  G_relu_sum  bound_softmax    tensor(0)  data/harness_small11.npz
12  (4, 4)  G_original            NaN   tensor(12)  data/harness_small12.npz
13  (4, 4)  G_original          ridge   tensor(12)  data/harness_small13.npz
14  (4, 4)  G_original  bound_sigmoid   tensor(12)  data/harness_small14.npz
15  (4, 4)  G_original  bound_softmax   tensor(12)  data/harness_small15.npz
16  (4, 4)   G_sigmoid            NaN   tensor(12)  data/harness_small16.npz
17  (4, 4)   G_sigmoid          ridge   tensor(12)  data/harness_small17.npz
18  (4, 4)   G_sigmoid  bound_sigmoid   tensor(28)  data/harness_small18.npz
19  (4, 4)   G_sigmoid  bound_softmax   tensor(12)  data/harness_small19.npz
20  (4, 4)  G_relu_sum            NaN   tensor(28)  data/harness_small20.npz
21  (4, 4)  G_relu_sum          ridge   tensor(12)  data/harness_small21.npz
22  (4, 4)  G_relu_sum  bound_sigmoid   tensor(12)  data/harness_small22.npz
23  (4, 4)  G_relu_sum  bound_softmax   tensor(12)  data/harness_small23.npz
24  (5, 5)  G_original            NaN    tensor(0)  data/harness_small24.npz
25  (5, 5)  G_original          ridge   tensor(30)  data/harness_small25.npz
26  (5, 5)  G_original  bound_sigmoid    tensor(0)  data/harness_small26.npz
27  (5, 5)  G_original  bound_softmax   tensor(23)  data/harness_small27.npz
28  (5, 5)   G_sigmoid            NaN    tensor(0)  data/harness_small28.npz
29  (5, 5)   G_sigmoid          ridge    tensor(0)  data/harness_small29.npz
30  (5, 5)   G_sigmoid  bound_sigmoid   tensor(50)  data/harness_small30.npz
31  (5, 5)   G_sigmoid  bound_softmax   tensor(50)  data/harness_small31.npz
32  (5, 5)  G_relu_sum            NaN    tensor(0)  data/harness_small32.npz
33  (5, 5)  G_relu_sum          ridge   tensor(30)  data/harness_small33.npz
34  (5, 5)  G_relu_sum  bound_sigmoid    tensor(0)  data/harness_small34.npz
35  (5, 5)  G_relu_sum  bound_softmax   tensor(23)  data/harness_small35.npz
36  (5, 6)  G_original            NaN   tensor(60)  data/harness_small36.npz
37  (5, 6)  G_original          ridge   tensor(60)  data/harness_small37.npz
38  (5, 6)  G_original  bound_sigmoid   tensor(60)  data/harness_small38.npz
39  (5, 6)  G_original  bound_softmax   tensor(60)  data/harness_small39.npz
40  (5, 6)   G_sigmoid            NaN   tensor(60)  data/harness_small40.npz
41  (5, 6)   G_sigmoid          ridge   tensor(60)  data/harness_small41.npz
42  (5, 6)   G_sigmoid  bound_sigmoid  tensor(150)  data/harness_small42.npz
43  (5, 6)   G_sigmoid  bound_softmax   tensor(60)  data/harness_small43.npz
44  (5, 6)  G_relu_sum            NaN  tensor(152)  data/harness_small44.npz
45  (5, 6)  G_relu_sum          ridge   tensor(60)  data/harness_small45.npz
46  (5, 6)  G_relu_sum  bound_sigmoid   tensor(60)  data/harness_small46.npz
47  (5, 6)  G_relu_sum  bound_softmax   tensor(60)  data/harness_small47.npz